name: front
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  freezed: ^2.5.2
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  injectable: ^2.4.2
  cloud_functions: ^5.0.1
  go_router: ^14.2.0
  url_launcher: ^6.3.0
  bloc: ^8.1.4
  file_picker: ^8.0.5
  http: ^1.2.1
  http_parser: ^4.0.2
  csv: ^6.0.0
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/


